export const APIService = {
  USER_MICRO_SERVICES: window.ENV.USER_SERVICE,
  MERCHANT_MICRO_SERVICES: window.ENV.MERCHANT_SERVICE,
  FORUM_MICRO_SERVICES: window.ENV.FORUM_SERVICE,
};

export const requestURLS = {
  LOGIN: "/api/auth/login",
  GET_USER: "/api/v2/user/dashboard",
  SIGNUP: "/api/auth/signup",
  RESET_PASSWORD: "/api/v2/user/reset-password",
  // SEND_MAGIC_URL: "/api/auth/magic-signup",
  // VERIFY_MAGIC_URL: "/api/auth/magic-url",
  // USER_OPERATIONS: "/core/user/",
  FORGOT_PASSWORD: "/api/auth/forget-password",
  VERIFY_OTP: "/api/auth/v3/check-otp",
  // GET_COMPANIES: "/v2/user/get-company",
  // GET_MODELS: "/v2/user/get-model",
  ADD_VEHICLE: "/v2/user/add_vehicle",
  GET_VEHICLES: "/v2/vehicle/vehicles",
  RESEND_MAIL: "/v2/vehicle/vehicle_details",
  CHANGE_EMAIL: "/api/v2/user/change-email",
  VERIFY_TOKEN: "/api/v2/user/verify-email-token",
  UPLOAD_PROFILE_PIC: "/api/v2/pictures",
  UPLOAD_VIDEO: "/api/v2/videos",
  CHANGE_VIDEO_NAME: "/api/v2/videos/convert_video",
  REFRESH_LOCATION: "/v2/vehicle/<carId>/location",
  CONVERT_VIDEO: "/api/v2/videos/convert_video",

  CONTACT_MECHANIC: "/api/merchant/contact_mechanic",
  RECEIVE_REPORT: "/api/mechanic/receive_report",
  GET_MECHANICS: "/api/mechanic",
  GET_PRODUCTS: "/api/shop/products",
  GET_SERVICES: "/api/mechanic/service_requests",
  BUY_PRODUCT: "/api/shop/orders",
  GET_ORDERS: "/api/shop/orders/all",
  RETURN_ORDER: "/api/shop/orders/return_order",
  APPLY_COUPON: "/api/shop/apply_coupon",

  ADD_NEW_POST: "/api/v2/community/posts",
  GET_POSTS: "/api/v2/community/posts/recent",
  GET_POST_BY_ID: "/api/v2/community/posts/<postId>",
  ADD_COMMENT: "/api/v2/commuinty/posts/<postId>/comment",
  VALIDATE_COUPON: "/api/v2/coupon/validate-coupon",
};
